"""FastAPI Router for Autonomous AI Speech Director & Scriptwriter Agent."""
import base64
import asyncio
from fastapi import APIRouter, HTTPException, Request
from typing import Dict, Any

# Universal import resolution
try:
    from backend.models.schemas import AgentScriptRequest, AgentProductionResponse, MultiSpeakerRequest, TTSResponse
    from backend.services.ai_agent_director import AIAgentDirectorService
    from backend.services.gemini_tts import GeminiTTSService
    from backend.services.audio_processor import AudioProcessor
    from backend.routers.tts import STYLE_PRESETS
except (ImportError, ModuleNotFoundError):
    from models.schemas import AgentScriptRequest, AgentProductionResponse, MultiSpeakerRequest, TTSResponse
    from services.ai_agent_director import AIAgentDirectorService
    from services.gemini_tts import GeminiTTSService
    from services.audio_processor import AudioProcessor
    from routers.tts import STYLE_PRESETS

router = APIRouter(prefix="/api/agent", tags=["AI Speech Director Agent"])
tts_service = GeminiTTSService()

@router.post("/generate-script", response_model=AgentProductionResponse)
async def generate_agent_script(request: AgentScriptRequest):
    """
    Autonomous AI Director Step 1 & 2:
    Writes, humanizes, and casts a multi-speaker audio story based on the user's prompt using Gemini AI.
    """
    try:
        data = await AIAgentDirectorService.create_and_humanize_audio_story(
            prompt=request.prompt,
            genre=request.genre,
            num_speakers=request.num_speakers,
            length=request.length,
            model_name=request.model_name,
            api_key=request.api_key
        )
        return AgentProductionResponse(
            status="success",
            title=data.get("title", "AI Audio Story"),
            synopsis=data.get("synopsis", "Generated by AI Speech Director"),
            genre=data.get("genre", request.genre),
            model_used=data.get("model_used", request.model_name or "gemini-2.5-flash"),
            characters=data.get("characters", []),
            dialogue=data.get("dialogue", [])
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/produce-audio", response_model=TTSResponse)
async def produce_agent_audio(request: MultiSpeakerRequest):
    """
    Autonomous AI Director Step 3:
    Synthesizes each character's dialogue line using Gemini Neural TTS and stitches the master audio drama.
    """
    if not request.dialogue:
        raise HTTPException(status_code=400, detail="Dialogue segments cannot be empty.")

    audio_segments = []
    total_characters = 0

    for idx, seg in enumerate(request.dialogue):
        style_obj = STYLE_PRESETS.get(seg.style_id, STYLE_PRESETS["natural"])
        prompt_with_style = f"{style_obj['promptPrefix']}{seg.text}"
        
        if request.language_code and request.language_code != "en-US":
            prompt_with_style = f"[Language: {request.language_code}] {prompt_with_style}"

        total_characters += len(seg.text)

        try:
            wav_bytes, duration = await tts_service.synthesize_speech(
                script=prompt_with_style,
                voice_id=seg.voice_id,
                engine_id=request.engine_id,
                api_key=request.api_key,
                custom_endpoint=request.custom_endpoint,
                output_format="wav"
            )
            audio_segments.append((wav_bytes, seg.pause_after_ms))
        except Exception as err:
            raise HTTPException(
                status_code=500,
                detail=f"Line {idx + 1} ({seg.speaker_name}) synthesis failed: {str(err)}"
            )

    # Stitch master audio
    master_wav = AudioProcessor.stitch_dialogue_segments(audio_segments)
    final_audio, content_type = AudioProcessor.transcode_audio(master_wav, request.output_format)
    
    total_duration = max(1.0, len(master_wav) / (24000 * 2))

    return TTSResponse(
        status="success",
        audio_base64=base64.b64encode(final_audio).decode("utf-8"),
        content_type=content_type,
        duration_seconds=round(total_duration, 2),
        sample_rate=24000,
        engine_used=request.engine_id,
        voice_id=f"Multi-Cast ({len(request.dialogue)} segments)",
        character_count=total_characters
    )
